version: "3.8"

services:

  jupyter-service:

    build:
      context: .
      dockerfile: jupyter.Dockerfile

    image: "jupyter-service:latest"

    ports:
      - "8888:8888"

    user: root

    init: true

    entrypoint:
      - "sh"
      - "-c"
      - "start-notebook.sh --no-browser ${EXTRA_ARGS}"

    environment:
      - "NB_UID=${NB_UID}"
      - "NB_GID=${NB_GID}"
      - "CHOWN_HOME=yes"
      - "CHOWN_HOME_OPTS=-R"

    volumes:
      - "./work:/home/jovyan/work"
      - "./security/cert:/home/jovyan/.local/cert"

    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4g"


  pluto-service:

    build:
      args:
        - "PLUTO_UID=${NB_UID}"
      context: .
      dockerfile: pluto.Dockerfile

    image: "pluto-service:latest"

    ports:
      - "1234:1234"

    init: true

    entrypoint:
      - "julia"
      - "-e"
      - >-
        using Pluto;
        Pluto.run(;
          launch_browser = false,
          host = "0.0.0.0",
          require_secret_for_open_links = false,
          require_secret_for_access = true);

    volumes:
      - type: bind
        source: "./work-pluto"
        target: "/home/pluto/work-pluto"

    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4g"
